[package]
org = "ballerina"
name = "ai_tests"
version = "1.5.2"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ai-native"
version = "1.5.2"
path = "../native/build/libs/ai-native-1.5.2.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ai-native"
version = "1.5.2"
path = "../native/build/libs/ai-native-1.5.2-tests.jar"
testOnly = true
